### ISSUE TITLE
(feature request) make app lockdown a locked phone

### ISSUE THREAD

**Issue by bungabunga** [wesaphzt/privatelock#6] opened 2019-09-08 17:02 UTC
this great app locks my unlocked device. well, actually it locks it down ≈ you can not unlock it with fingerprint anymore which is safer.

it would be great if that would also happen when the device is already locked - at some physical stress it'd become locked down, possible to unlock only with pin/password.

**Comment by wesaphzt** [comment] 2019-09-08 18:10
Only being able to unlock via PIN is a system limitation that Google won't fix, but it does make it safer in that regard though less convenient.
Although I'm not quite sure what you're saying, can you expand?
What do you mean "physical stress"?

**Comment by zoktiik** [comment] 2019-09-08 20:53
@wesaphzt He's probably talking about having Private Lock, when triggered via the threshold, use its device admin locking to force PIN input, even if the phone is already locked manually via the power button.
This doesn't seem to be a feature of PluckLockEx, and I don't know if it's possible to force PIN unlocking when the phone was locked manually.
@bungabunga is this what you meant?

**Comment by wesaphzt** [comment] 2019-09-08 22:04
Thanks @zoktiik. 
If that's what @bungabunga's talking about then yes, it's possible to do what you mentioned.
The locking functionality is just disabled while the screen is off or on lock screen.

**Comment by bungabunga** [comment] 2019-09-09 02:17
sorry guys for not being clear enough. yes, I'd like only that the app would act the same, locked or unlocked. use case: if you are dealing with the police they could use physical force on you to unlock device with your fingerprints. with this app on it wouldn't be possible.

**Comment by wesaphzt** [comment] 2019-09-09 12:38
It's a good idea to have the option! And easy enough to implement.
Added in https://github.com/wesaphzt/privatelock/commit/813b948f1995f9162856e15cfab9ae0857786cb6
Works fine from my testing but I don't have fingerprint to test directly, so let me know if there's any issues, but there shouldn't be any difference to be honest.

**Comment by wesaphzt** [comment] 2019-09-15 14:16
Is anyone able to test?
I get a small issue where when triggered in the background, turning the screen on immediately locks the screen again, like it's been queued up in the background to execute when the screen is on.
Not sure if this is a minor phone/LineageOS annoyance or more widespread.

**Comment by zoktiik** [comment] 2019-09-15 17:30
@wesaphzt I couldn't reproduce your issue on my Pixel 2; the screen changed to a device admin lock when I shook it, and it only turned off the screen when I already had it on. Whenever I turned the screen back on, the phone had already been device admin-locked.

**Comment by wesaphzt** [comment] 2019-09-15 17:56
Great thanks for the feedback!
Just tested on a friends phone with stock ROM and like you, no issue.
I'll have to assume it's specific to LineageOS in that case which can't really be helped.
Closing the ticket.

**Closed by wesaphzt** 2019-09-15 17:56 UTC
